[project]
name = "deepmidi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=3.6.0",
    "deeplotx>=0.4.15",
    "jupyter>=1.1.1",
    "music21>=9.7.1",
    "requests>=2.32.4",
    "vortezwohl>=0.0.2",
]
